### ISSUE TITLE
SERVER升级3.3后无法用3.1.3的connector连接

### ISSUE THREAD

**Issue by arthasking123** [taosdata/taos-connector-dotnet#88]
提示：Failed to execute SQL: show databases, ErrCode: 286, ErrMessage: Version not compatible
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      TDengine.Driver.TDengineError: code:[0x11e],error:Version not compatible
         at TDengine.Driver.Impl.WebSocketMethods.BaseConnection.SendJsonBackJson[T1,T2](String action, T1 req)
         at TDengine.Driver.Impl.WebSocketMethods.Connection.Connect()
         at TDengine.Driver.Client.Websocket.WSClient..ctor(ConnectionStringBuilder builder)      
         at TDengine.Driver.Client.DbDriver.Open(ConnectionStringBuilder builder)

没有最新的connector吗？

**Comment by huskar-t** [comment]
If you use the native connection, you need to upgrade the client's dynamic library
